### ISSUE TITLE
Problema con png

### ISSUE THREAD

**Issue by yabirgb** [smnlpz/Troya-Mosaic#4]
Cuando se encuentra un png en la carpeta para construir el mosaico numpy lanza una excepción proque intenta multiplcar una matriz de 4 dimensiones con una de 3 (si hay archivos jpg).

Posibles soluciones:

- verificar que todos los archivos tienen el mismo numero de componentes para los colores 
- Avisar de este error y no empezar la ejecución

**Comment by smnlpz** [comment]
En las pruebas que he hecho no ha habido problema entre archivos JPG y PNG, el error al que te refieres creo que viene del formato RGB. Por defecto, se leen y almacenan las imágenes en RGB, pero si entra alguna imagen en RGBA (RGB con transparencia)  da error al hacer la comparación entre las imágenes por tener distintas dimensiones.

Haré una comprobación del espacio de colores que se usa y convertiré todas las imágenes añadidas a RGB, gracias!
